language: ruby
rvm:
  - 2.2.0
gemfile:
  - Gemfile
services:
  - mysql
before_script:
  - mysql -e 'create database railsexample_test;'
deploy:
  provider: heroku
  api_key:
    secure: "35ff9cbd-90ed-4951-a6c4-d6d970c12878"  