language: ruby
rvm:
  - 2.2.0
gemfile:
  - Gemfile
services:
  - postgresql
before_script:
  - psql -c 'create database railsexample_test;' -U postgres  
deploy:
  provider: heroku
  api_key:
    secure: "35ff9cbd-90ed-4951-a6c4-d6d970c12878"  
  run: "rake db:migrate"  

notifications:
  email:
    recipients:
      - anderson.luis.rib@gmail.com
      - anderson_lr@hotmail.com
    on_success: [always|never|change] # default: always
    on_failure: [always|never|change] # default: always  